# Generated by Django 4.1.1 on 2022-09-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='id',
            new_name='Id',
        ),
    ]
