# Generated by Django 4.1.1 on 2022-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_remove_ad_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
