# Generated by Django 4.1.1 on 2022-09-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ad_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["username"],
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.RenameField(
            model_name="author",
            old_name="location_id",
            new_name="location",
        ),
    ]
