# Generated by Django 4.1.1 on 2022-09-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_rename_category_id_ad_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="author_id",
            new_name="author",
        ),
    ]
